version: "3"

services:
  db:
    image: couchdb:2.3.0
    hostname: mycouchdb
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
      NODENAME: 172.26.130.218
    ports:
      - "5984:5984"
      - "5986:5986"
      - "4369:4369"
      - "9100-9200:9100-9200"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
       - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - db