---
- name: Uninstall old versions of docker
  tags: 'docker'
  become: yes
  apt:
    name: ['docker', 'docker-engine', 'docker.io']
    state: absent

- name: Install dependencies
  tags: 'docker'
  become: yes
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'python-setuptools', 'software-properties-common']
    state: latest
    install_recommends: no
    update_cache: yes

- name: Add Docker apt repository key
  tags: 'docker'
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker apt repository and update apt cache
  tags: 'docker'
  become: yes
  apt_repository:
    repo: "deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
    mode: '644'
    update_cache: yes
    state: present

- name: Install docker
  tags: 'docker'
  become: yes
  apt:
    name: ['docker-ce']
    state: latest
    install_recommends: no
    update_cache: yes

- name: Install docker-compose
  tags: 'docker'
  become: yes
  pip:
    name: ['docker-compose']
    state: latest

- name: Install jinja2
  tags: 'docker'
  become: yes
  pip:
    name: ['jinja2']
    state: latest

- name: add proxy to docker environment
  become: yes
  lineinfile:
    dest: /lib/systemd/system/docker.service
    regexp: '(Restart=always)'
    insertafter: '^\n'
    line: "{{ item.line }}"
  with_items:
    - { line: 'Environment="HTTP_PROXY=http://wwwproxy.unimelb.edu.au:8000/" "HTTPS_PROXY=http://wwwproxy.unimelb.edu.au:8000/"' }

- name: add proxy to docker image
  become: yes
  lineinfile:
    dest: /etc/default/docker
    regexp: '^\n'
    insertafter: '^\n'
    line: "{{ item.line }}"
  with_items:
    - { line: 'http_proxy="http://wwwproxy.unimelb.edu.au:8000"' }
    - { line: 'https_proxy="http://wwwproxy.unimelb.edu.au:8000"' }
    - { line: 'ftp_proxy="http://wwwproxy.unimelb.edu.au:8000"' }
    - { line: 'no_proxy=localhost,127.0.0.1,127.0.1.1,ubuntu' }

- name: reload config
  become: yes
  shell: systemctl daemon-reload

- name: Start docker
  become: yes
  shell: systemctl restart docker
