version: "3"

services:
  db:
    image: couchdb:3.0.0
    hostname: mycouchdb
    environment:
      COUCHDB_USER: "ccc"
      COUCHDB_PASSWORD: "happyccc"
    ports:
      - "5984:5984"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
       - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db