---


- name: Get updated files from git repository
  become: yes
  git:
    repo: "https://{{ githubuser | urlencode }}:{{ githubpassword | urlencode }}@github.com/Damonzhl/backend.git"
    dest: /tmp/backend

- name: update the backend file
  tags: 'git'
  become: yes
  command: "cp -r /tmp/backend /couchdb"