---
- name: add github ssh key
  copy:
    src: "{{project_working_directory}}/COMP90024-2019S1-Team7/config/GitHub"
    dest: /home/ubuntu/.ssh/GitHub
    owner: ubuntu
    group: ubuntu
    mode: 0600
# copy GitHub private key to server

- name: configure ssh to use ansible key for github.com
  template:
    src: "{{project_working_directory}}/COMP90024-2019S1-Team7/config/ssh_config"
    dest: /home/ubuntu/.ssh/config
    owner: ubuntu
    group: ubuntu
    mode: 0644
# configure ssh to use ansible key for github.com

- name: clone source code from git
  git:
    repo: ssh://git@github.com/HanxunHuangLemonBear/COMP90024-2019S1-Team7.git
    key_file: /home/ubuntu/.ssh/GitHub
    dest: '{{ remote_working_directory }}'
