---


- name: Get updated files from git repository
  become: yes
  git:
    repo: "https://{{ githubuser | urlencode }}:{{ githubpassword | urlencode }}@github.com/Damonzhl/backend.git"
    dest: /tmp/backend
    update: yes
    force: yes

- name: rm the exiting code
  tags: 'git'
  become: yes
  command: "rm -fr /couchdb/twitterHarvester"

- name: cp code file
  tags: 'git'
  become: yes
  command: "cp -r /tmp/backend/twitterHarvester /couchdb/twitterHarvester"

- name: Run docker compose stop
  tags: 'git'
  become: yes
  command: "chdir={{ couchdb_dir }} docker-compose stop"

- name: Run docker compose start
  tags: 'git'
  become: yes
  command: "chdir={{ couchdb_dir }} docker-compose up -d"
-

