- hosts: all
  vars_files:
    - host_vars/couchdb.yaml
  gather_facts: false
  roles:
    - role: common
    - role: volumes
    - role: docker
    - role: couchdb
    
- hosts: COMP90024
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/ssh/benjaminnectar.pem
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
