# Common vars
availability_zone: melbourne-qh2-uom

# Volume
volumes:
  - vol_name: vol-1
    vol_size: 60
  - vol_name: vol-2
    vol_size: 60
  - vol_name: vol-3
    vol_size: 60
  - vol_name: vol-4
    vol_size: 60
    


# Security group
security_groups:
  - name: demo_ssh
    description: "Demo security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_http
    description: "Demo security group for HTTP and TCP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_http
    description: "Demo security group for HTTP and TCP"
    protocol: tcp
    port_range_min: 4369
    port_range_max: 4369
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_http
    description: "Demo security group for HTTP and TCP"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5986
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_http
    description: "Demo security group for HTTP and TCP"
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9200
    remote_ip_prefix: 0.0.0.0/0
  

# Instance
instances:
  - name: cluster-1
    volumes: ['vol-1']
  - name: cluster-2
    volumes: ['vol-2']
  - name: cluster-3
    volumes: ['vol-3']
  - name: cluster-4
    volumes: ['vol-4']

instance_image: 45225edb-66d8-4fd0-bf41-132a31a18166
instance_key_name: benjaminnectar
instance_flavor: uom.mse.2c9g
